inventory_exception_job:
  cron: "45 4 * * *"
  class: "GenerateExceptionsJob"
  description: "This job generates inventory exceptions"

inventory_location_group_exception_job:
  cron: "55 4 * *"
  class: "GenerateLocationGroupExceptionsJob"
  description: "Identify and generate location group exceptions"

crawl_job:
  cron: "15 3 * * *"
  class: "ShiftSourcesJob"
  description: "Move orders and shipments forward one day"
