inventory_exception_job:
  cron: "45 4 * * *"
  class: "GenerateExceptionsJob"
  description: "This job generates inventory exceptions"

inventory_location_group_exception_job:
  cron: "55 4 * *"
  class: "GenerateLocationGroupExceptionsJob"
  description: "Identify and generate location group exceptions"

crawl_job:
  cron: "15 3 * * *"
  class: "CrawlJob"
  description: "Move projections forward one day"

orders_reset:
  cron: "30 3 * * *"
  class: "OrdersReset"
  description: "Recreate orders for new day"

shipments_reset:
  cron: "30 4 * * *"
  class: "ShipmentsReset"
  description: "fully ship out orders within 7 days and partially 7 days after"
